Pull request - data loader
rdevon/cortex pull request #1
Opened 2017-07-14 01:27 UTC by lhd231

Data loader for text files

2017-07-18 23:03 UTC, ghost commented
I looked at Noah's code. It looks good, the tfrecords file is storing the pairs of samples and labels. The code doesn't acquire the data on its own, but I am not sure if this is a necessity. 
Also for both our data, we might want to add a code for accessing the tfrecords file.

2017-07-19 02:36 UTC, rdevon requested changes

2017-07-19 02:36 UTC, rdevon commented on data/labels_sample.txt
> +1.000000000000000000e+00
So why do we need this file? It seems like it can be generated on its own. In addition, why are they floats if they are labels?

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +def load_file(name,delimiter=',',type=np.float32):
You need to delint your code. I will add lint functionality to this repo soon.

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +'''
Please place the descriptions of the script before imports.

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +    if len(args) == 2:
I suggest using argparse to deal with arguments. The record is just going to go into the current directory, which is bad practice. For now, include an argument for the output directory / file. I suggest though eventually we have a default "home" for data that is user-defined.

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +
Is there any check to make sure the features / labels are the right format?

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +data_file = "./data_sample.txt"
I see the need for testing data, but I'm not sure it belongs here. For one, make a unit test that runs on this data. Second, if it's really necessary for testing, can it just be generated (using a random number generator), rather than take up space in the repo. Finally, I suggest using a temporal directory (such as in `/tmp`) to store test data after its generated (and then erase it).

2017-07-19 02:36 UTC, rdevon commented on data/snp.py
> +    print "Save completed.  File is: ./text_records.tfrecords"
We need to move to logging. 

@lhd231 @srinjaypaul @edamaraju I had logging in cortex. Can we just import that functionality here and now?

2018-05-08 15:14 UTC, rdevon commented
Out of date. DataLoader has changed quite a bit. Any chance this will be updated?

2018-06-13 12:40 UTC, closed without merging